### ISSUE TITLE
Curate a spreadsheet of initial algorithms

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#1]

**Comment by teju85** [comment]
Going forward we'll NOT be relying on nvgraph. Thus, we need to be migrating out of cugraph, the things that cuml currently uses in nvgraph. For starters: Everything nvgraph related in [https://github.com/rapidsai/cuml/blob/branch-0.13/cpp/src_prims/sparse/spectral.h](spectral.h)

Just a note for cuml-devs, to complete this process at our end.
1. We'll need to remove [https://github.com/rapidsai/cuml/blob/branch-0.13/cpp/src_prims/sparse/nvgraph_wrappers.h](nvgraph_wrappers.h)
2. Remove all references of nvgraph from [https://github.com/rapidsai/cuml/blob/branch-0.13/cpp/CMakeLists.txt](CMakeLists.txt) and [https://github.com/rapidsai/cuml/blob/branch-0.13/cpp/test/CMakeLists.txt](test/CMakeLists.txt)
3. Similarly also from [https://github.com/rapidsai/cuml/blob/branch-0.13/cpp/include/cuml/cluster/spectral.hpp](spectral.hpp) and [https://github.com/rapidsai/cuml/tree/branch-0.13/cpp/src/spectral/spectral.cu](spectral.cu)

**Comment by cjnolet** [comment]
Just to capture an initial inventory of shared prims, based on discussions so far (Please feel free to list any others here as well):

Sparse prims:
- Weak CC
- Spectral clustering
- COO/CSR conversion routines
- CSR L1 & Max normalization
- Transposed sum

API:
- handle
- communicator

**Comment by teju85** [comment]
being explicit...

API:
- device/host allocators
  - default allocator
  - RMM based allocator
  - and maybe, even cub based caching allocator

**Comment by divyegala** [comment]
@cjnolet @teju85 can this issue be closed?
