### ISSUE TITLE
[ENH] Deprecate `myMax` and similar functions

### ISSUE THREAD

**Issue by Nyrio** [rapidsai/raft#1025]
Follows [this discussion](https://github.com/rapidsai/raft/pull/979#discussion_r1024464274). @achirkin and @cjnolet can perhaps say more about the reasons behind deprecating these functions and why they existed in the first place?

Another concern: right now we can't really compile with Clang anyway, but I seem to remember using `std::max` in device functions doesn't compile with Clang?

**Comment by achirkin** [comment]
`std::max` is a constexpr [since C++14](https://en.cppreference.com/w/cpp/algorithm/max). Could it have something to do with that?

**Comment by ahendriksen** [comment]
I believe that `std::max` and `fmaxf` are not defined the same way. 

In any case, they produce different instruction sequences. 

eg:
```
#include <algorithm>

typedef float T;

__global__ void kernel(T* x, T* y, T* z) {
    z[0] = std::max(x[0], y[0]);
    __syncthreads();
    z[1] = fmaxf(x[1], y[1]);
}
```

Produces 

```
// std::max
 FSETP.GEU.AND P0, PT, R0, R9, PT 
 FSEL R9, R9, R0, !P0 
// fmaxf:
 FMNMX R11, R0, R11, !PT 
```

See: https://godbolt.org/z/YnocKz4j1

**Comment by Nyrio** [comment]
@ahendriksen You are correct. NVCC adds some CUDA intrinsics to the `std` namespace so that they are defined on device (such as `sqrt`), in which case the generated code would be exactly the same. But that's not the case for `std::max` which behaves differently from the intrinsic (and can be used in device functions due to being defined as `constexpr`).

I'm leaning towards using the `std::` versions on host and the CUDA intrinsics on device, for Clang compatibility, using conditional compilation, e.g:

```c++
template <typename T>
constexpr RAFT_INLINE_FUNCTION auto sqrt(const T& x)
{
    #ifdef __CUDA_ARCH__
    return ::sqrt(x);
    #else
    return std::sqrt(x);
    #endif
}
```

**Comment by Nyrio** [comment]
Btw, the [Math API documentation](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH.html#group__CUDA__MATH) says:

> Note also that due to implementation constraints, certain math functions from std:: namespace may be callable in device code even via explicitly qualified std:: names. However, such use is discouraged, since this capability is unsupported, unverified, undocumented, not portable, and may change without notice.

So regardless of Clang compatibility issues, it's wise to go by this recommendation.

**Comment by ahendriksen** [comment]
In C++20, there is `std::is_constant_evaluated` that would allow us to fall back to an equivalent constexpr expression for the fmaxf functions. See, e.g., [this stackoverflow answer](https://stackoverflow.com/a/68076572). But this may not be worth the effort.

In summary, can we say: 
- Use std::max in constant expressions
- Do not deprecate raft::myMax because in performance-sensitive code, it will/might be faster?

Tbh, I suspect that the urge to deprecate `raft::myMax` is caused in some part by its name. Perhaps I can suggest `raft::math::max` in a dedicated namespace?

**Comment by Nyrio** [comment]
> In summary, can we say:
>  - Use std::max in constant expressions
>  - Do not use std::max by accident on floating point values, because it is explicitly "unsupported, unverified, undocumented, not portable, and may change without notice".

Exactly. CUDA's max only differs from the standard max for floating-point numbers. Typical use in const expressions is with integers.

> Do not deprecate raft::myMax because in performance-sensitive code, it will/might be faster?

Why would `raft::myMax` be any faster than the new `raft::max`? The generated code is exactly the same for floating-point numbers.

> Tbh, I suspect that the urge to deprecate raft::myMax is caused in some part by its name. Perhaps I can suggest raft::math::max in a dedicated namespace?

Oh, hold on, you might not be aware that this is done already: https://github.com/rapidsai/raft/blob/79e1ce854329bd655f2b02c86e6ec39165eebfc6/cpp/include/raft/core/math.hpp#L166-L224

Btw, closing this issue since the PR has been merged

**Comment by ahendriksen** [comment]
Ah great! I did not know that `::max()` works as well!
