### ISSUE TITLE
[BUG] IVF flat incorrect distance values with int8 data

### ISSUE THREAD

**Issue by tfeher** [rapidsai/raft#1058]
**Describe the bug**
The distance values returned with IVF flat search method might be incorrect in certain cases

IVF flat search is used by ANN refinement (if the dataset is in device memory) #1052. The Python tests of refinement revealed this problem. This only happens with int8 data (and not with uint8). IVF flat search has specific kernels for different data types, this might point towards a bug in the int8 specialization.

Note: the returned neighbor indices are correct, only the distance values show this problem.

**Steps/Code to reproduce bug**
To reproduce the issue:
1. Uncomment the following lines
https://github.com/tfeher/raft/blob/c34952ba42ca313e280f89fe4a0bc6a495a03852/python/pylibraft/pylibraft/test/test_refine.py#L127-L128

2. Run the refinement test
```bash
pytest pylibraft/test/test_refine.py -k test_refine_dtypes
```
Output:
```
>       assert np.mean(diff) < eps
E       assert 0.41265658 < 0.001
E        +  where 0.41265658 = <function mean at 0x14cd30085e50>(array([[0.46209675, 0.3915514 , 0.41272217, 0.41572857, 0.40346152,\n        0.37558016, 0.39662588, 0.36034888, 0.3658...373, 0.33194792, 0.20105657,\n        0.38698354, 0.3945595 , 0.40543446, 0.3377944 , 0.3658476 ]],\n      dtype=float32))
E        +    where <function mean at 0x14cd30085e50> = np.mean

pylibraft/test/test_ivf_pq.py:79: AssertionError
========================================================================================================== short test summary info ==========================================================================================================
FAILED pylibraft/test/test_refine.py::test_refine_dtypes[device-int8-l2_expanded-True-100] - assert 0.41855982 < 0.001
FAILED pylibraft/test/test_refine.py::test_refine_dtypes[device-int8-l2_expanded-True-1024] - assert 0.41032004 < 0.001
FAILED pylibraft/test/test_refine.py::test_refine_dtypes[device-int8-l2_expanded-True-37] - assert 0.40580684 < 0.001
FAILED pylibraft/test/test_refine.py::test_refine_dtypes[device-int8-l2_expanded-False-100] - assert 0.41458178 < 0.001
FAILED pylibraft/test/test_refine.py::test_refine_dtypes[device-int8-l2_expanded-False-1024] - assert 0.41299787 < 0.001
FAILED pylibraft/test/test_refine.py::test_refine_dtypes[device-int8-l2_expanded-False-37] - assert 0.41265658 < 0.001
========================================================================================== 6 failed, 42 passed, 24 skipped, 20 deselected in 7.37s ==========================================================================================
```

**Expected behavior**
Passing tests with int8 data.

**Additional context**
The current C++ unit test only inspect the distance values if the neighbor indices are different. https://github.com/rapidsai/raft/blob/11c51059c401d344097b86d9b9ab4a6f464e9410/cpp/test/neighbors/ann_utils.cuh#L195-L199

The unit test shall be extended with a test of the actual distance values. The actual distance between the neighbor and the query vector shall be inspected, and compared to a naive distance calculation. Such test is done in the IVF-PQ [python tests ](https://github.com/rapidsai/raft/blob/11c51059c401d344097b86d9b9ab4a6f464e9410/python/pylibraft/pylibraft/test/test_ivf_pq.py#L46)and in the refinment test. But such test is not yet applied for the IVF-flat results.

Note, even IVF PQ had an issue with the distance values, but that was fixed in  https://github.com/rapidsai/raft/pull/892

**Comment by Nyrio** [comment]
The fix has been merged.
