### ISSUE TITLE
[FEA] Exception-based macro and single header file for all error checkers

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#11]
This was proposed in #7 (https://github.com/rapidsai/raft/pull/7#discussion_r425401511)

**Comment by cjnolet** [comment]
As @seunghwak mentions:
> Yes, and I think we'd better move every error check macros/functions (RAFT_EXPECTS, RAFT_FAIL, NCCL_TRY, CUDA_TRY, ...) to one error.hpp file.

**Comment by seunghwak** [comment]
Not sure who has right to assign tasks, but can any one assign this and https://github.com/rapidsai/raft/issues/8 to me?

Or let me know if someone else is already working on this.
