### ISSUE TITLE
Is there a way create a handle from an external cuda stream? Or get the pointer to the raft stream for use by other libraries?

### ISSUE THREAD

**Issue by rahedges** [rapidsai/raft#1123]
I have an application that is using cupy for matrix manipulation.  I would like to use the `fused_l2_nn_argmin` function to find nearest vectors.   I would like to utilize  a cuda stream for asynchronous operation.   I would like to use the same cuda stream for the cupy oprerations and the raft operations.

  I see the the `fused_l2_nn_argmin`  can accept a `handle` argument so that the operation can be run on a stream.   I would like to be able to use the same stream for the cupy calculations and the raft handle.   Is there a way to create a raft handle from a cupy stream? This would be similar to the `cupy.cuda.ExternalStream` function.

Alternatively, is there a way to get the pointer to the raft Stream so that it could be passed to the `cupy.cuda.ExternalStream()` function.

In cupy I can do the following

```python
str_ptr = cp.cuda.runtime.streamCreate()
cp_str= cp.cuda.ExternalStream(str_ptr)
cp_str.use():
    # Matrix operations using the cupy stream
   fused_l2_nn_argmin(in1, in2, output)  # raft operation will use default stream

```

In raft I can do
```python
raft_stream=Stream()
raft_handle=Handle(raft_stream)
str_ptr = cp.cuda.runtime.streamCreate()
cp_str= cp.cuda.ExternalStream(str_ptr)
cp_str.use():
    # Matrix operations using the cupy stream
    fused_l2_nn_argmin(in1, in2, output, handle=raft_handle) # this will use the raft_stream, 
```

What I would like to do (method 1):
```python
str_ptr = cp.cuda.runtime.streamCreate()
cp_str= cp.cuda.ExternalStream(str_ptr)
raft_external_stream = Stream(str_ptr)
raft_handle= Handle(raft_external_stream)

cp_str.use():
    # Matrix operations using the cupy stream
   fused_l2_nn_argmin(in1, in2, output, handle=raft_handle) # this will use the same stream

```
Method 2:
``` python
raft_stream=Stream()
raft_handle=Handle(raft_stream)
cp_str=  cp.cuda.ExternalStream(raft_stream.get_ptr())  # wrap the raft stream as a cupy stream
cp_str.use():
    # Matrix operations using the raft stream
    fused_l2_nn_argmin(in1, in2, output, handle=raft_handle) # this will use the raft_stream, 

```
Since cuML can use a raft handle, this would be more broadly applicable to any application that is utilizing cuda streams and a mix of cupy and rapids.

Any help will be appreciated, thanks.

**Comment by cjnolet** [comment]
@rahedges, 

Thanks for creating an issue about this. It's really a fair ask and I've created a pull request (#1125) for it which allows you to create a handle from a `cupy` stream pointer. Will the following work for you?

Here's how to implement your first example:
```python
import cupy
from pylibraft.common import Handle

s = cupy.cuda.Stream()
raft_handle = Handle(stream=s.ptr)
...
``` 

Here's the second example:
```python
import cupy
from pylibraft.common import Stream

raft_stream = Stream()
cp_str = cp.cuda.ExternalStream(raft_stream.get_ptr())
```

**Comment by rahedges** [comment]
@cjnolet 

Thanks, I was able to build this and integrate the update into my  dev environment.  It works for me; now I can use the same stream for Cupy operations as well as anything in Rapids that can use a Handle.
 
Note: 
To do the build as specified in the `README.md`:
```shell
./build.sh raft-dask pylibraft libraft tests bench --compile-libs
```
I had to add `gtest` and `nccl` to the mamba environment.  They could be added to environment file `all_cuda-115_arch-x86_64.yaml`
