### ISSUE TITLE
[FEA] upgrade CUDA stream pool

### ISSUE THREAD

**Issue by afender** [rapidsai/raft#115]
We should consider leveraging [RMM CUDA stream pool](https://github.com/rapidsai/rmm/pull/659) to replace the [custom implementation in RAFT ](https://github.com/rapidsai/raft/blob/4593c21455d26434ed06a36c4b962bb88cee2522/cpp/include/raft/handle.hpp#L130)

An important aspect that I think should be reconciled regardless is the API to acquire a stream from the pool.

**Comment by teju85** [comment]
I'm all in favor of code reuse. I don't see any big issues with this in cuML. But I'd like to hear from @cjnolet on this one. Because, in MNMG algo's like kNN we end up querying for *all* of the streams at once and then use them to launch work onto GPUs!

> re: API to acquire a stream from the pool

FWIW, the proposed `get_stream` approach should just work fine with cuML.

**Comment by harrism** [comment]
Also please consider using `rmm::cuda_stream` and `rmm::cuda_stream_view` in RAFT, cuML, and cuGraph as well.

**Comment by teju85** [comment]
Sounds like a good idea. The only caveat is that using `rmm::cuda_stream` will cause a ripple change in all of RAFT/cuML/cuGraph, as we expose a `cudaStream_t` on almost *all* methods! Maybe in the interim we could just use the underlying `cudaStream_t` object from `rmm::cuda_stream`? Is that possible @harrism ?

**Comment by harrism** [comment]
You would never use `rmm::cuda_stream` for a function parameter, as it is an owning wrapper. You would use it (or `rmm::cuda_stream_pool`) for *creating* streams. For function parameters, use `rmm::cuda_stream_view`, which is implicitly constructable from `cudaStream_t` and so should not break your APIs.
