### ISSUE TITLE
[ENH] Do not create temporary device memory pools in IVF-Flat, IVF-PQ and balanced k-means

### ISSUE THREAD

**Issue by Nyrio** [rapidsai/raft#1167]
These memory pools can currently exist concurrently with each other or with a user-defined memory pool, creating problems of both performance and memory limits/control. It should instead be the responsibility of the user to create an appropriate memory pool, and the algorithms should use the resources attached to the raft handle.

Places where memory pools are currently created:
 - `cluster::detail::build_hierarchical`
 - `ivf_flat::detail::search`
 - `ivf_pq::detail::extend`
 - `ivf_pq::detail::build`
 - `ivf_pq::detail::search`

Typical code used to create these pools:
https://github.com/rapidsai/raft/blob/0076101e69c03bab03c9cb022d2e4c519bce60af/cpp/include/raft/spatial/knn/detail/ivf_pq_build.cuh#L1173-L1174

@cjnolet's message that explains why we want to avoid doing that: https://github.com/rapidsai/raft/pull/1113#discussion_r1084391622

Note: once we do this change, we should also update our benchmarks to reflect the typical/proper use of these pools (note that the use of pools in benchmarks can slow down benchmarks significantly though if setup for each instance of the benchmark class, bonus points if we can reuse the pools properly).

cc @achirkin @tfeher

**Comment by cjnolet** [comment]
This has since been completed. Unfortunately, we are still using managed memory in places on the user's behalf but the usage of pools behind the scenes has been fixed.
