### ISSUE TITLE
[FEA] Separate IVFs into individual memory chunks.

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#1170]
This has been strongly requested for the FAISS integration and for true incremental add support. It also matches more closely to the current FAISS implementation and allows the `copyFrom()` implementation to be much more straightforward.

**Comment by tfeher** [comment]
**Background**

Currently both IVF-Flat an IVF-PQ stores its index as a single array of all vectors. This has a drawback when we extend the index: we need to recreate the whole index to insert the new values.

Both method has the same coarse level clustering:

- we groups the points into n_lists clusters
- each cluster store all its vectors (interleaved and padded) in one chunk lets call this cluster data
- The cluster data has to be stored in one chunk, for efficient search.
- Currently the index is just a concatenation of cluster data for each cluster

**Tasks**

- Store IVF-Flat index in separate array for each cluster #1176
- Store IVF-PQ index in separate array for each cluster

**Amortize cost of growing the array**
- Discuss if it is necessary to preallocate larger space for list, that would allow growth without reallocating and moving to new list.

**Comment by cjnolet** [comment]
I also want to note here that after we separate the lists into their own individual arrays, we will need to use the new [CodePacker](https://github.com/facebookresearch/faiss/pull/2625) API in FAISS to perform the transformation of the CPU/GPU indexes into the RAFT interleaved indexes.

**Comment by achirkin** [comment]
Resolved via #1249 and #1271
