### ISSUE TITLE
[FEA] Separate index into individual list arrays for IVF-Flat

### ISSUE THREAD

**Issue by tfeher** [rapidsai/raft#1176]
**Is your feature request related to a problem? Please describe.**
Currently both IVF-Flat an IVF-PQ stores its index as a single array of all vectors. This has a drawback when we extend the index: we need to recreate the whole index to insert the new values.

See https://github.com/rapidsai/raft/issues/1170#issuecomment-1403838530 for general background information

**Describe the solution you'd like**
1. Store IVF-Flat index in separate array for each cluster
2. Store IVF-PQ index in separate array for each cluster
3. Amortize cost of growing the array

**Details: IVF-Flat**
- IVF-flat index structure is described https://github.com/rapidsai/raft/blob/7c12b1e38de47a3d686f082b456c24b6eec381b0/cpp/include/raft/neighbors/ivf_flat_types.hpp#L99-L118

- The concatenated list of vectors are stored in [data_](https://github.com/rapidsai/raft/blob/7c12b1e38de47a3d686f082b456c24b6eec381b0/cpp/include/raft/neighbors/ivf_flat_types.hpp#L281).
- We maintain the corresponding [indices_](https://github.com/rapidsai/raft/blob/7c12b1e38de47a3d686f082b456c24b6eec381b0/cpp/include/raft/neighbors/ivf_flat_types.hpp#L282) from the original dataset .
- The clusters are described with [sizes and offsets](https://github.com/rapidsai/raft/blob/7c12b1e38de47a3d686f082b456c24b6eec381b0/cpp/include/raft/neighbors/ivf_flat_types.hpp#L283-L284)

**Proposed changes IVF-Flat**
Build
- The dataset could be stored in a `std::vector<device_mdarray<T, extent_2d<IdxT>, row_major>>`, where each cluster would have a separate mdarray to store its vectors.
- Vectors are added to the dataset in the [extend](https://github.com/rapidsai/raft/blob/7c12b1e38de47a3d686f082b456c24b6eec381b0/cpp/include/raft/spatial/knn/detail/ivf_flat_build.cuh#L119) method.
- Instead of [calculating new offsets, and moving old data](https://github.com/rapidsai/raft/blob/7c12b1e38de47a3d686f082b456c24b6eec381b0/cpp/include/raft/spatial/knn/detail/ivf_flat_build.cuh#L182-L213)  for all clusters, we need to move the _cluster data_ only for the culsters that get new vectors. 
- If we store the clusters in an mdarray that have some empty rows at the end as reserve capacity, then the previous step is not needed, the new vectors can be copied directly after the existing ones (next step by build_index_kernel).
- [build_index_kernel](https://github.com/rapidsai/raft/blob/7c12b1e38de47a3d686f082b456c24b6eec381b0/cpp/include/raft/spatial/knn/detail/ivf_flat_build.cuh#L222) is called on the lists that are getting extended.

Search
- pass modified structs to search kernel https://github.com/rapidsai/raft/blob/7c12b1e38de47a3d686f082b456c24b6eec381b0/cpp/include/raft/spatial/knn/detail/ivf_flat_search.cuh#L871-L874
- Use the separate list arrays instead of the offset https://github.com/rapidsai/raft/blob/7c12b1e38de47a3d686f082b456c24b6eec381b0/cpp/include/raft/spatial/knn/detail/ivf_flat_search.cuh#L743
- 
Additional steps:
- [Refinement](https://github.com/rapidsai/raft/blob/7c12b1e38de47a3d686f082b456c24b6eec381b0/cpp/include/raft/neighbors/detail/refine.cuh#L98-L113) also [builds an IVF-Flat index](https://github.com/rapidsai/raft/blob/7c12b1e38de47a3d686f082b456c24b6eec381b0/cpp/include/raft/spatial/knn/detail/ivf_flat_build.cuh#L366), it has to be updated.
- [Saving and loading](https://github.com/rapidsai/raft/blob/7c12b1e38de47a3d686f082b456c24b6eec381b0/cpp/include/raft/spatial/knn/detail/ivf_flat_build.cuh#L407-L410) the dataset has to be updated
- run benchmarks

**Amortize costs of index growth**
- If needed, then we probably want a user parameter that would control how much extra space do we allocate

**Comment by achirkin** [comment]
Resolved via #1271
