### ISSUE TITLE
[QST] Should we include standard library?

### ISSUE THREAD

**Issue by MatthiasKohl** [rapidsai/raft#122]
**What is your question?**
I ran into an issue (which was easy to solve) when including `<raft/mr/allocator.hpp>`:
Basically, if you include nothing else, the standard library namespace isn't defined and the compiler doesn't know what to do with the `std::size_t` types in that file. It's easy enough to just include `<cstddef>` before including `<raft/mr/allocator.hpp>` but maybe it makes sense to do this directly in raft.
Should I look for these cases in raft and submit a PR?

**Comment by divyegala** [comment]
@wphicks you solved this one, right?

**Comment by wphicks** [comment]
No; I just encountered this error myself in the cuml codebase. We should probably still go through and make sure that we've taken care of this everywhere.

**Comment by cjnolet** [comment]
@MatthiasKohl if you are still interested in opening up a PR for this, it would definitely be welcome. In the meantime, we have been adding things like `<cstdint>` as we encounter them.

**Comment by MatthiasKohl** [comment]
@cjnolet sure, I'll look into this tomorrow. I can try to create a small script that just includes any file from raft and compiles it to see if a standalone include works

**Comment by MatthiasKohl** [comment]
Sorry for not following up here, I've been quite busy, and I don't know when I'll have the time to look into this.
In the mean-time, this seems like a minor issue, so possibly we can continue to check for this on a case-by-case basis.
