### ISSUE TITLE
RAFT: CUDA 12 Conda Packages

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/raft#1278]
Pushing for CUDA 12 Conda package builds of libraries for RAPIDS 23.04. This issue is for tracking that work.

Requirements (please recheck):

```[tasklist]
### Developer tasks
- [x] I've confirmed the list below is correct (or updated if not)
```

```[tasklist]
### Toolkit dependencies from Conda
- [ ] https://github.com/conda-forge/staged-recipes/pull/21723
- [ ] https://github.com/conda-forge/staged-recipes/pull/21350
- [ ] https://github.com/conda-forge/staged-recipes/pull/22125
- [ ] https://github.com/conda-forge/staged-recipes/pull/22052
- [ ] https://github.com/conda-forge/staged-recipes/pull/21901
- [ ] https://github.com/conda-forge/staged-recipes/pull/21916
- [ ] https://github.com/conda-forge/staged-recipes/pull/21924
- [ ] https://github.com/conda-forge/staged-recipes/pull/21953
```

```[tasklist]
### RAPIDS Conda dependencies
- [ ] https://github.com/rapidsai/rmm/issues/1207
```

```[tasklist]
### Other dependencies from Conda using CUDA
- [ ] https://github.com/conda-forge/nccl-feedstock/issues/82
- [ ] https://github.com/conda-forge/ucx-split-feedstock/issues/116
```

```[tasklist]
### Deprecated dependencies from Conda using CUDA ( please see PR https://github.com/rapidsai/raft/pull/1202 )
- [ ] https://github.com/conda-forge/faiss-split-feedstock/issues/65
```

```[tasklist]
### Test only dependencies from Conda using CUDA
- [ ] https://github.com/conda-forge/cupy-feedstock/issues/139
```

**Comment by bdice** [comment]
cuda-cccl is not a dependency for any RAPIDS packages. RAPIDS usually uses newer (and sometimes patched) versions of CCCL fetched by rapids-cmake, and won't be needing the `cuda-cccl` packages.

**Comment by bdice** [comment]
Also needs `nccl` and `ucx` with CUDA support listed somewhere.

**Comment by jakirkham** [comment]
For now will leave `cuda-cccl` just so we know it is used in some form. How exactly we handled that we can follow up after the general discussion around it has settled.

Good to know about `-dev` packages being used at runtime. The `-dev` packages are produced out of a split package that also produces the dynamic & static library packages. So knowing one of them is needed is sufficient. We can take a closer look when it comes time to rebuild.

Thanks for reminding me 🙏 Had forgotten these 🤦‍♂️ They are now in the other dependencies list.

**Comment by cjnolet** [comment]
I agree w/ @bdice, we don't explicitly depend on anything from `cuda-cccl` currently.

**Comment by jakirkham** [comment]
Thanks Corey! 🙏

Since `cuda-nvcc` is going to depend on `cuda-cccl`, am going to leave it.

Noted that `faiss` is going away, but have left that item in the list for now. Believe merging that PR should check that box, but we can do this manually if that ends up being needed.

**Comment by cjnolet** [comment]
@jakirkham this LGTM. Just looked back through the dependencies to verify. `cupy` is only a test dependency and everything else is covered.

**Comment by bdice** [comment]
Working on builds with the `nvidia` channel here: https://github.com/rapidsai/raft/pull/1353

**Comment by jakirkham** [comment]
Current work using `nvidia` channel packages in PR ( https://github.com/rapidsai/raft/pull/1388 )
