### ISSUE TITLE
[BUG] RAFT header conflicts

### ISSUE THREAD

**Issue by bryevdv** [rapidsai/raft#128]
**Describe the bug**
RAFT headers do not play nicely with some other RAPIDS libraries because of duplicated names

in rapids-js, just doing 
```
include <cugraph/graph.hpp>
```
results in:

```
./../../.cache/cpm/raft/39a4ee56e5ca66c2be3eb2b78767b9d0d46759cc/cpp/include/raft/cudart_utils.h:52: error: "CUDA_TRY" redefined [-Werror]
   52 | #define CUDA_TRY(call)                                                        \
      | 
In file included from ../../../cudf/src/node_cudf/utilities/error.hpp:20,
                 from ../../../cudf/src/node_cudf/scalar.hpp:17,
                 from ../../../cudf/src/node_cudf/column.hpp:17,
                 from ../../src/node_cugraph/graph_coo.hpp:17,
                 from ../../src/graph_coo.cpp:15:
../../../.cache/cpm/cudf/6bbbff12b33dfcdeef951b16babffd1472c03bdb/cpp/include/cudf/utilities/error.hpp:102: note: this is the location of the previous definition
  102 | #define CUDA_TRY(call)                                            \
      | 
```

Currently to mitigate we have an `internal/graph.hpp` header to do this:

```
#ifdef CUDA_TRY
#undef CUDA_TRY
#endif
#ifdef CHECK_CUDA
#undef CHECK_CUDA
#endif
#include <cugraph/graph.hpp>
#ifdef CHECK_CUDA
#undef CHECK_CUDA
#endif
#ifdef CUDA_TRY
#undef CUDA_TRY
#endif
```

But it would be better if these RAPIDS tools could coordinate to avoid these clashes. 

cc @trxcllnt

**Comment by bryevdv** [comment]
This still seems worth addressing.

**Comment by AjayThorve** [comment]
+1 Facing similar issues while building raft with cuml, for `node-rapids` bindings.

**Comment by cjnolet** [comment]
@bryevdv @AjayThorve @trxclln

tIs the problem here is related to conflicting names which are defined in multiple projects or are these conflicts defined only in RAFT but having problems because somehow the RAFT headers are being installed in different locations? If it's the former, I would recommend we centralize the conflicting names into RAFT (potentially prefixed w/ a `RAFT` specifier) to remove duplication. If the latter, we might want to consider consolidating the RAFT header installs. Any thoughts?

**Comment by bryevdv** [comment]
cc @trxcllnt 

@cjnolet I assume the former. E.g. `CUDA_TRY` appears to be defined here in Raft:

https://github.com/rapidsai/raft/blob/c2e5a09c0222f0cf49e1bdf889173d3162202dd5/cpp/include/raft/cudart_utils.h#L56

and here in cudf

https://github.com/rapidsai/cudf/blob/branch-21.12/cpp/include/cudf/utilities/error.hpp#L102

**Comment by jlowe** [comment]
Ran into the same problem described by @bryevdv trying to use RAFT and cuDF APIs in a compilation unit.

**Comment by cjnolet** [comment]
I will be creating a PR for this shortly, though we've agreed to add the new macros and deprecate the old ones rather than renaming. In the meantime, I will wrap the current functions w/ conditionals to test if it's been defined, though.
