### ISSUE TITLE
[FEA] mdspan/mdarray-based utility to copy a pointer to device iff it is not already on device

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#1299]
This is a very useful utility in FAISS and something that we should support in raft so that we can have a unified means of handling both device and host inputs (and copying to temporary device buffers only if needed). 

The challenge here is that what we really seem to want is some type of object that can act like a view all the time, but which also owns the underlying memory only as needed. This is not something our current mdspan/mdarray infrastructure can support, so we will need to build something for this case. 

@mhoemmen has suggested we use something like the [kokkos::DualView](https://github.com/kokkos/kokkos/wiki/Kokkos::DualView) which can mirror device and host views with container(s) underneath to copy between temporary buffers as needed, keeping them up to date between host and device. I think this could work in our case, but as Mark points out, we would want to make it read-only on the host side so that the device side isn't copied back to the host.

**Comment by mhoemmen** [comment]
@cjnolet wrote:
> mhoemmen has suggested we use something like the Kokkos::DualView....

Please please do not get the impression that I suggested using Kokkos::DualView.  DualView does not give a good example of how to solve this problem.

I'll discuss this offline with you; I've given talks about this and have slides ready to share.
