### ISSUE TITLE
[BUG] Documentation contains the wrong index url for `pip`

### ISSUE THREAD

**Issue by stucash** [rapidsai/raft#1377]
I am running a Debian 10 variant, pip version is 23.0.1, my python version is 3.10.5 and I am install raft in a virtual environment.  I don't use conda. 

`pip install pylibraft-cu11 --extra-index-url=https://pypi.ngc.nvidia.com`

This command failed with following error (full stacktrace):

```
Using cached pylibraft_cu11-23.2.0.tar.gz (6.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ntr37f6q/pylibraft-cu11_9880525f73d74ff28085eebedde60aaf/setup.py", line 137, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      FileNotFoundError: [Errno 2] No such file or directory: 'ERROR.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by stucash** [comment]
I am not sure whether this is due to the fact that libraft-headers are not installed (and if without conda, one has to build from source); if it is, I'll have to install the required libraries and build from source. I found, not only libraft-headers needs to be built from source, RMM is also conda-only.  

Does this mean to use raft, I'll have to install either conda or build from source?

**Comment by cjnolet** [comment]
@stucash thanks for opening and issue about this. 

> Does this mean to use raft, I'll have to install either conda or build from source?

The RAFT wheels contain all of the RAFT pieces so you should not have to build or use anything else within RAFT. What version of CUDA toolkit and model of GPU do you have installed?

@vyasr @sevagh have either of you seen this error before?

**Comment by stucash** [comment]
Thanks for the quick reponse, my `nvidia-smi` yields following information and I have a single card of Nvidia GTX 1070Ti:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.56.06    Driver Version: 520.56.06    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   54C    P0    36W / 180W |    787MiB /  8192MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      5324      G   /usr/lib/xorg/Xorg                477MiB |
|    0   N/A  N/A      5715      G   xfwm4                               6MiB |
|    0   N/A  N/A     91200      G   ...375511171156693346,131072      231MiB |
+-----------------------------------------------------------------------------+

```

**Comment by stucash** [comment]
> There is a minor bug that we know about and are fixing regarding providing better error messages, but the underlying problem here is that your installation command is using the wrong URL. It should be:
> 
> ```
> pip install pylibraft-cu11 --extra-index-url=https://pypi.nvidia.com
> ```
> 
> (note the lack of the `ngc` subdomain).

Thanks for that! Just so you know my line of command was taken directly from READ.ME of this repo, probably it means it needs to be updated.

**Comment by cjnolet** [comment]
@stucash Thanks so much for trying the corrected link! I'm going to convert this issue into a bug report so that we can prioritize fixing our docs.
