### ISSUE TITLE
[FEA] `raft::linalg::map*` primitives to support types that are not a power of 2

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#1413]
Before recent changes to consolidate the `writeOnlyUnaryOp` and other map-based primitives, we were able to support datatypes with sizes which are not a power of 2. This feature was broken in this refactor and it's no longer allowing the use of these primitives for custom types, as an example.

cc @eschmidt-nvidia @achirkin @tfeher @ahendriksen

**Comment by achirkin** [comment]
As a workaround while I am on my leave, you could try to disable the vectorization for the non-power-of-two-sized types. You can do this by specializing this `ratio_selector::ignoring_alignment`:
https://github.com/rapidsai/raft/blob/a98295b516ef58bc855177077860bab2a2a76d77/cpp/include/raft/linalg/detail/map.cuh#L116-L120

**Comment by ahendriksen** [comment]
Should this go in the 23.04 release or does it have lower priority?

**Comment by cjnolet** [comment]
@ahendriksen it's not worth holding up the release or doing a hotfix, but we should aim to fix it in 23.06 (hopefully soon).
