### ISSUE TITLE
[BUG][RAFT+FAISS] Missing resource_factory virtual destructor

### ISSUE THREAD

**Issue by alexanderguzhva** [rapidsai/raft#1425]
**Describe the bug**
RAFT + FAISS won't compile, https://github.com/facebookresearch/faiss/pull/2521

**How to fix**
`virtual ~resource_factory() {};` is needed in raft/core/resource/resource_types.hpp
After such a change it becomes possible to compile Raft + FAISS (some other changes are needed, but they are unrelated to Raft core)

**Comment by cjnolet** [comment]
@alexanderguzhva we should be able to change the RAFT version in the FAISS PR to `branch-23.06` and this issue should be fixed.
