### ISSUE TITLE
[BUG] Missing `jaccard` metric

### ISSUE THREAD

**Issue by viclafargue** [rapidsai/raft#1647]
It looks like the `jaccard` metric is missing from [the implementation](https://github.com/rapidsai/raft/blob/88bf3248bacf6d281555f104f222c463b44f5ea3/cpp/include/raft/distance/distance-inl.cuh#L259-L309). Is there any reason for it?

**Comment by csadorf** [comment]
I think the metric is not actually missing, but only supported for sparse inputs.

**Comment by viclafargue** [comment]
I did not notice this. Thanks, I will close this issue then.
