### ISSUE TITLE
[BUG] raft::linalg::reduce won't compile when InType != OutType

### ISSUE THREAD

**Issue by Nyrio** [rapidsai/raft#165]
**Describe the bug**
I am reducing a boolean matrix to an integer vector (cf code sample in the section below).
I only need `coalescedReduction`, but the `reduce` function instantiates `stridedReduction` too and this is where the problem happens, at [line 150 of strided_reduction.cuh](https://github.com/rapidsai/raft/blob/b055cf862a599fd45537d21a309edd8a6e06da4c/cpp/include/raft/linalg/strided_reduction.cuh#L150): the `if` statement is not determined at compile time (it's not a C++17 `if constexpr`) so it attempts to compile `stridedSummationKernel` even if the input and output types are different, in which case it can't compile.

Note that at the moment I solved the problem for my use case by calling directly `coalescedReduction` instead of `reduce`.

**Steps/Code to reproduce bug**
This is approximately what my code looks like:
```cuda
bool* in;
int* out;
raft::linalg::reduce(
  out, in, N, N, 0, true, true, stream, false,
  [] __device__(bool value, int idx) {
    return static_cast<int>(value);
  },
  raft::Sum<int>(), raft::Nop<int>());
```

Compilation error:
```
include/raft/linalg/strided_reduction.cuh(152): error: no instance of function template "raft::linalg::stridedSummationKernel" matches the argument list
argument types are: (int *, const __nv_bool *, int, int, int, lambda [](__nv_bool, int)->int)
detected during: instantiation of "void raft::linalg::stridedReduction(OutType *, const InType *, IdxType, IdxType, OutType, cudaStream_t, __nv_bool, MainLambda, ReduceLambda, FinalLambda) [with InType=__nv_bool, OutType=int, IdxType=int, MainLambda=lambda [](__nv_bool, int)->int, ReduceLambda=raft::Sum<int>, FinalLambda=raft::Nop<int, int>]"
```

**Expected behavior**
The reduction should support different input and output types as suggested by the template parameters and the docs.

**Comment by divyegala** [comment]
@Nyrio now that RAFT uses C++17, do you think you could submit a PR with a fix for this?

**Comment by Nyrio** [comment]
> do you think you could submit a PR with a fix for this?

@divyegala Yes, I will.
