### ISSUE TITLE
[FEA] CPU-only package and environments for ANN-benchmarks

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#1735]
We're running into this while trying to test the CPU-only algorithm(s) on hardware that don't contain GPUs. The current `libraft-ann-bench` package brings in cudatoolkit and the actual underlying C++ benchmark implementation is making calls to cuda runtime. In order for us to make fair comparisons with our reproducible benchmarks, we need to be able to support running hnswlib benchmark in a CPU-only mode.

**Comment by achirkin** [comment]
Just a note that https://github.com/rapidsai/raft/pull/1661 already does not require CUDA to run hnswlib at runtime and the change to make it compile without CUDA would be trivial as well.

**Comment by achirkin** [comment]
Update: I went ahead and added the last bits to make hnswlib benchmarks compile and run without CUDA
(though ATM some changes to the main `cpp/CMakeLists.txt` required for this, which I didn't do).

**Comment by cjnolet** [comment]
Closed by #1773
