### ISSUE TITLE
[FEA] Move `label/classlabels.cuh` from cuml to RAFT

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#179]
The MSF currently returns a colors array with colors that are not always likely to be drawn from a monotonically increasing set.

The algorithm to connect a knn graph currently uses the colors array as-is, but the algorithm would be more efficient and save a lot of memory if the array sizes didn't depend on the max label but instead on the number of unique labels. This can be accomplished easily by re-labeling the colors array so they are drawn from a monotonically increasing set.

**Comment by divyegala** [comment]
This was done in #181
