### ISSUE TITLE
[BUG] Lanczos solver isn't reproducible even with seed

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#195]
We noticed this specifically on CUDA 11.2. It looks like the spectral clustering and lanczos solver aren't returning the same results when given the same input and seed. We noticed this in UMAP specifically in cuML.

**Comment by trivialfis** [comment]
Right now I'm sticking with random init.  But will look into other places as well.

**Comment by cjnolet** [comment]
@trivialfis, yeah that should work for now. Unfortunately, since it's too late to scrape through this and figure out the cause in time for 0.19, we should try to figure out what's going on here at some point because the spectral init has been shown to preserve more global structure than random init.

I found this bug by placing debug outputs in the spectral init for umap in cuml and found that executing it twice with the same random seem yielded different results. It could be as simple as a seed being overlooked somewhere, though I believe this was working before CTK 11.2 which makes me think something (or an assumption) has since broken, perhaps from one of the dependent libraries.
