### ISSUE TITLE
[ENH] Re-apply the matrix::select_k heuristics

### ISSUE THREAD

**Issue by achirkin** [rapidsai/raft#1975]
Re-run and apply [select_k/generate_heuristic](https://github.com/rapidsai/raft/blob/branch-23.12/cpp/scripts/heuristics/select_k/generate_heuristic.ipynb).

After #1878 is merged, the radix-based implementation should be faster than before for some inputs.
If the radix-based implementation is faster than the legacy FAISS implementation in all cases, this would be a good moment to get rid of the old code. Otherwise, we should investigate further the reasons for being slower in the remaining cases.

**Comment by benfred** [comment]
Done w/ #1985
