### ISSUE TITLE
[QST] How to avoid cuda resource warning when using cargra?

### ISSUE THREAD

**Issue by FakeEnd** [rapidsai/raft#2071]
**What is your question?**

When I use cagra in pytorch with python api, I repeat computation cargra in nn.Module Class as one layer in my model and it gives following warning.
I see warning is something with C++, so I wondering how to fix python code to avoid such problem?

```
device_resources = DeviceResources()
build_params = cagra.IndexParams(metric="sqeuclidean")

def carge_implementation(embedding_2d, k_neighbors):
    index = cagra.build(build_params, embedding_2d.detach(), handle=device_resources)
    distances, neighbors = cagra.search(cagra.SearchParams(),
                                        index, embedding_2d.detach(),
                                        k_neighbors, handle=device_resources)
    device_resources.sync()
    return distances, neighbors

class ANN(nn.Module):

    def __init__(self):
        super(ANN, self).__init__()

    def forward(self, embedding, k_neighbors):
        xxxxxx

        distances, neighbors = carge_implementation(embedding, k_neighbors)

        return xxxx
```

`[W] [17:45:37.312065] [raft::neighbors::cagra::build] the default cuda resource is used for the raft workspace allocations. This may lead to a significant slowdown for this algorithm. Consider using the default pool resource(`raft::resource::set_workspace_to_pool_resource`) or set your own resource explicitly (`raft::resource::set_workspace_resource`).
[W] [17:45:37.312125] [raft::ivf_pq::build] the default cuda resource is used for the raft workspace allocations. This may lead to a significant slowdown for this algorithm. Consider using the default pool resource (`raft::resource::set_workspace_to_pool_resource`) or set your own resource explicitly (`raft::resource::set_workspace_resource`).
[W] [17:45:37.490805] [raft::ivf_pq::extend] the default cuda resource is used for the raft workspace allocations. This may lead to a significant slowdown for this algorithm. Consider using the default pool resource (`raft::resource::set_workspace_to_pool_resource`) or set your own resource explicitly (`raft::resource::set_workspace_resource`).
[W] [17:45:37.494786] [raft::ivf_pq::search] the default cuda resource is used for the raft workspace allocations. This may lead to a significant slowdown for this algorithm. Consider using the default pool resource (`raft::resource::set_workspace_to_pool_resource`) or set your own resource explicitly (`raft::resource::set_workspace_resource`).
[W] [17:45:38.419188] [raft::neighbors::cagra::search] the default cuda resource is used for the raft workspace allocations. This may lead to a significant slowdown for this algorithm. Consider using the default pool resource (`raft::resource::set_workspace_to_pool_resource`) or set your own resource explicitly (`raft::resource::set_workspace_resource`).`

**Comment by cjnolet** [comment]
Hi @FakeEnd 


This warning has actually been removed in the latest nightlies for the 24.02 version because it's pretty much always recommended to use a pool allocator as the default allocator. We use RMM memory manager, which uses cudaMalloc and cudaFree by default but [the vector search tutorial](https://docs.rapids.ai/api/raft/nightly/vector_search_tutorial/#device-memory-resources) has instructions for setting a pool allocator as the default allocator. If you are using Python, you can find a similar example in the RMM readme (at https://github.com/rapidsai/rmm).

**Comment by cjnolet** [comment]
[here](https://github.com/rapidsai/rmm#memoryresource-objects) is the Python example for setting an RMM pool allocator.

**Comment by cjnolet** [comment]
@FakeEnd since you are using PyTorch, another thing worth pointing out is that RMM supports PyTorch so the memory pool you create can be shared by both. We have found this to be a really useful feature when working across library boundaries.

**Comment by FakeEnd** [comment]
> @FakeEnd since you are using PyTorch, another thing worth pointing out is that RMM supports PyTorch so the memory pool you create can be shared by both. We have found this to be a really useful feature when working across library boundaries.

Thank you:)
