### ISSUE TITLE
[FEA] `raft-ann-bench` improve file naming and path consistency

### ISSUE THREAD

**Issue by fy** [rapidsai/raft#2154]
**Is your feature request related to a problem? Please describe.**

Currently most file names and paths (dataset files, index files) are hardcoded ([example](https://github.com/rapidsai/raft/blob/branch-24.04/python/raft-ann-bench/src/raft-ann-bench/run/conf/wiki_all_10M.json)). 

**Describe the solution you'd like**

Use templates for the names and paths. For example, in [wiki_all_10M.json#L15C7-L18C47](https://github.com/rapidsai/raft/blob/d403ab46c44aa316b56029b73077e33b598c578f/python/raft-ann-bench/src/raft-ann-bench/run/conf/wiki_all_10M.json#L15C7-L18C47),

```json
      "name": "hnswlib.M16.ef50",
      "algo": "hnswlib",
      "build_param": { "M": 16, "efConstruction": 50, "numThreads": 56 },
      "file": "wiki_all_10M/hnswlib/M16.ef50",
```
we can infer the index name from `build_param`: `f"{dataset}/{algorithm}/M{M}.ef{efConstruction}"`.

**Comment by cjnolet** [comment]
If this issue is about the format of the json files in the codebase, I would disregard them as they are legacy. Those json files are automatically generated using the Python scripts now.
