### ISSUE TITLE
[BUG] conda libraft package includes static library

### ISSUE THREAD

**Issue by msarahan** [rapidsai/raft#2175]
**Describe the bug**
I'm not sure if this is truly a bug, or just a design choice that I don't understand. There is a libraft-static package, and this is where I'd expect to find the 	`libraft.a` static library. And it is there. The problem is that it is *also* in the libraft package. Since this static library is 550 MB, it leads to some pretty significant bloat when people only want the shared library.

**Expected behavior**
I personally would remove `libraft.a` from the `libraft` package, keeping it in libraft-static. I will put up a PR if you agree with this idea.

**Environment details (please complete the following information):**
conda, rapidsai channel. Full package: `libraft-23.12.00-cuda12_231206_g9e2d6277_0/`

**Comment by cjnolet** [comment]
Thanks @msarahan. You are correct, the libraft-static is only intended to be included in its own static conda package and should not be getting packaged up with the libraft shared library package.
