### ISSUE TITLE
[BUG] pairwise distances and fused L2 1-NN kernels is limited by launch config

### ISSUE THREAD

**Issue by mdoijade** [rapidsai/raft#221]
**Describe the bug**
pairwise distances and fused L2 1-NN kernels which are based on contractions_NT class launches CTAs proportional to the input size.
Due to this it can only launch kernels where number of blocks in `Y` is less than 65536 as this is the max limit of cuda kernel grid size.
This severely limits the input size which these kernels can process.
This should be converted to be grid strided kernels launching CTAs based on GPU occupancy heuristics.

**Steps/Code to reproduce bug**
make the `n` in any of the pairwise distances/fused L2-NN kernel to be of size 65536x64 and run the kernel

**Expected behavior**

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of RAFT install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Additional context**

**Comment by mdoijade** [comment]
@teju85  FYI.

**Comment by cyy857** [comment]
Hello , is there any update on this issue?

**Comment by mdoijade** [comment]
this PR addresses this issue - https://github.com/rapidsai/raft/pull/232

**Comment by mdoijade** [comment]
closing this issue as the fix PR is merged now in branch-21.08 .
