### ISSUE TITLE
[QST] Question about VectorSearch_QuestionRetrieval.ipynb

### ISSUE THREAD

**Issue by hdeep03** [rapidsai/raft#2230]
**What is your question?**

In the last cell of the [VectorSearch_QuestionRetrieval.ipynb notebook](https://github.com/rapidsai/raft/blob/branch-24.04/notebooks/VectorSearch_QuestionRetrieval.ipynb), it runs %time which only times the current line(which is empty), should it instead run the %%time magic command to actually time the search, or is the performance result from that cell real?

**Comment by lowener** [comment]
Good catch, I created PR #2231 to fix this mistake
