### ISSUE TITLE
[BUG] Cagra To hnsw, the search api not use search param ef

### ISSUE THREAD

**Issue by Presburger** [rapidsai/raft#2363]
We recently tried to convert CAGRA to HNSW using RAFT's built-in API. We found that the `ef` parameter was not passed to `hnswlib`. Moreover, even when using `setEf` to set the `ef` parameter, there are concurrency issues.
https://github.com/rapidsai/raft/blob/b66b269ab6dcda48aef3a6ed9e7f604e99471d72/cpp/include/raft/neighbors/hnsw.hpp#L122

**Comment by divyegala** [comment]
@Presburger thank you for bringing this up, I'll look into this.

Could you please describe the concurrency issues?

**Comment by Presburger** [comment]
@divyegala https://github.com/rapidsai/raft/blob/b66b269ab6dcda48aef3a6ed9e7f604e99471d72/cpp/src/raft_runtime/neighbors/hnsw.cpp#L31 
The hardcoded file name here might not be concurrency-friendly?

**Comment by divyegala** [comment]
@Presburger thanks for pointing that out. I'll also add a random number to that file name so it is more concurrency friendly.
