### ISSUE TITLE
[FEA] Updates needed for lds/sts methods in device_loads_stores.cuh

### ISSUE THREAD

**Issue by teju85** [rapidsai/raft#251]
**Is your feature request related to a problem? Please describe.**
The current versions of lds/sts methods in [device_loads_stores.cuh](https://github.com/rapidsai/raft/blob/branch-21.06/cpp/include/raft/common/device_loads_stores.cuh) accepts a pointer. This means, compiler might not always be able to prove the input pointers are from shared memory range. This could mean that at times these functions end up emiting generic load/store instructions, which *could* also affect compiler's ability to issue vectorized memory accesses! To make sure we aid compiler in always emitting the right code, we should update these methods to do very similar thing that the `ldg` methods in this header are doing, but with a prior `__cvta_generic_to_shared` call.

**Describe the solution you'd like**
Here's an example (unverified!) of the change for `lds` method. We need to do this similarly for all `lds` and `sts` overloaded methods.
```
DI void lds(float (&x)[4], float* addr) {
  auto s4 = __cvta_generic_to_shared(reinterpret_cast<float4*>(addr));
  asm volatile("ld.shared.v4.f32 {%0, %1, %2, %3}, [%4];"
                      : "=f"(x[0]), "=f"(x[1]), "=f"(x[2]), "=f"(x[3])
                      : "l"(s4));
}
```

**Additional context**
Tagging @mdoijade to implement this fix and verify that these changes indeed do not affect anything in the distance prims classes. Also tagging @vinaydes for his similar needs in RF kernels.

**Comment by mdoijade** [comment]
this issue can be closed now as the fix PR is merged - https://github.com/rapidsai/raft/commit/b266d54cc6fb70dfcb730d5c7ba603b0133f2808
