### ISSUE TITLE
[FEA] Move k-means from cuml to RAFT

### ISSUE THREAD

**Issue by afender** [rapidsai/raft#28]
cuML exposes a Kmeans feature. Another Kmeans implementation has been introduced as part of moving Spectral clustering to RAFT.
We should avoid multiplying implementations for the same feature.

We could move cuML's kmeans backend to RAFT and use it in spectral clustering (and potentially in cuGraph as well later on).

**Comment by cjnolet** [comment]
Prioritizing this as a 22.06 task to support the cuann work.
