### ISSUE TITLE
[BUG] Upgrade to python 3.7 and CUDA 10.1

### ISSUE THREAD

**Issue by afender** [rapidsai/raft#32]
Support new CUDA/Python versions. CUDA 10.1 and python 3.7 as new defaults.

https://github.com/rapidsai/raft/blob/b122d5003079c7b5b3ed942ebe24765bcfb7d6c1/ci/local/build.sh#L3

**Comment by divyegala** [comment]
@dantegd does this need to be updated? I see that the equivalent script in cuML was also updated a year ago https://github.com/rapidsai/cuml/blob/eaa2add5bdd4543df61d95d764826cfdb0eff6ac/ci/local/build.sh#L6
