### ISSUE TITLE
[FEA] Consolidate sparse/dense matrix descriptor implementations

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#348]
We have a few different matrix descriptor objects available in RAFT currently for wrapping the 3 arrays in sparse formats. Off the top of my head, I can think of the `raft::sparse::COO` object used in many of the sparse primitives, `sparse_matrix_t` used in the spectral clustering code / lanczos solver, and the `Graph_COO` used in the MST prim. 

It would be nice to see an RAII object like `raft::sparse::COO` and `sparse_matrix_t` used but which enables each of the 3 arrays to have a different templated datat type. I also like the inheritance pattern used in the `sparse_matrix_t` implementations because it can make for easier interactions with primitives that can enforce constraints on input. I also like the additional healper functions on the `sparse_matrix_t`, such as `fill()` and it would be nice to see some of the existing sparse primitives, such as those used for conversions, reductions, and linear algebra, to potentially become exposed as methods on the object. This would allow users to manipulate the object in a more object-oriented manner while still keeping the primitives themselves able to be invoked as functions... might need to think about that more but wanted to create this issue as a placeholder. 

@ChuckHastings @BradReesWork @seunghwak I'm wondering if there might be an opportunity to introduce some elements from the core cugraph object here so that they can be shared between cuml and cugraph (as well as other downstream projects).

**Comment by cjnolet** [comment]
Now that `mdspan` and `mdarray` have been merged into 22.04, we can start on a sparse abstraction pending #499

**Comment by cjnolet** [comment]
I've been thinking through a good design for this change and talking with a few folks about things to consider and ideal designs. I want to capture a few notes for things:

1. We should separate the structure itself (connections) from the possibility for weights/values. @mhoemmen has suggested that maybe we capture the structure in `graph_view` while capturing the structure+weights in a `sparse_matrix<graph_view>`. 
2. It's important that we capture expectations in the APIs so our users know what side effects, if any, to expect from different functions- for example, we should differentiate between views that might change weights/values from those that might change structure from those that might require a completely new sparse matrix or graph to be allocated.
3. We need to consider the design of the memory owning containers and the intended user experience for invoking functions whitch might need to change structure. 

@mhoemmen proposed a really nice way to think about this problem, using "solid", "liquid", "gas" nomenclature- 
- solid = object is completely immutable (`sparse_matrix_view<const T, graph_view<const S, const D>>`)
- liquid = changes can be made to values/weights but not to structure (`sparse_matrix_view<T, graph_view<const S, const D>>`)
- gas = changes can be made to values/weights and structure (`sparse_matrix<T, graph<S, D>>`). this invalidates any existing views

I like this way of thinking about the problem as it also follows a lot of the paradigms used by GraphBLAS. 

Similar to the GraphBLAS, I also propose that the `gas`-level owning-container be somewhat opaque in the way that it can be passed around directly but also allows the ability to `initialize()` or `reinitialize()` the structure and values. 

Owning containers for each of the 3 states could look like this:
- solid: `sparse_matrix<const T, graph<const S, const D>>`
- liquid: `sparse_matrix<T, graph<const S, const D>>`
- gas: `sparse_matrix<T, graph<S, D>>`

We have several algorithms in RAFT and cuML that support these 3 types of objects- 
- in cuml, for example, we have several algorithms that accept completely immutable, read-only sparse matrices as input and then perform a matrix multiplication that immediately turns them dense. 
- in raft, we have several primitives that either take in a solid or liquid and either produce a liquid or a gas. 


Things to consider:
1. How do we invalidate views?
2. How do we manage the lifespan of 'gas' object to make it painful for users? Currently on RAFT, the user can allocate the gas object with structure/value sizes if that information is known, but they can also allocate an empty object which can be resized within the function that populates it.

**Comment by mhoemmen** [comment]
@cjnolet Thanks for tagging me! : - )

There are other possible "states of the matrix."  For example, 4-array CSR (start offsets, end offsets, column indices, values) fixes the allocations, but not the structure.  It's a good way to represent a matrix whose rows might have duplicate column indices, and/or to leave space for future expansion at the end of each row.  Users may want to "pack" 4-array CSR into the usual 3-array CSR, for the many libraries that only work with 3-array CSR.

> How do we manage the lifespan of 'gas' object to make it painful for users?

If phase transitions move-from an object into a new object, and if moved-from objects are emptied (like `std::vector`), then users will be forced to drop the old object and use the new object.

**Comment by cjnolet** [comment]
@mfoerste4 we use `mdspan` already to represent dense data and associated metadata. The plan is to eventually update all of cuml's APIs to use `mdspan` in addition to these new sparse structures. 

From an API perspective, these collapse potentially multiple function arguments into a single argument so we can build APIs (like SVM for example) which are agnostic to whether the inputs are dense or sparse. I really don't think we need any other structures for unifying these APIs outside of providing overloads for `mdspan` and these new sparse structures. 

Initial implementations of these new sparse structures have been merged now, so we should be able to use them in cuml to make the svm changes.
