### ISSUE TITLE
[FEA] Adjust directories and algorithm locations to align better with categories

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#361]
Alignging the directories w/ higher-level categories will make the API much easier to use and the prims much easier to find. So far, we've been discussing having these potential directories inside `include/raft/`:

- `formats/`
- `gen/`
- `spatial/`
- `matrix/`
- `solvers/`
- `comms/`

We could also potentially unify the sparse and dense primitives or keep them separated into their own top-level directories. 

Tagging the usual @divyegala @wphicks @dantegd @ChuckHastings @BradReesWork @seunghwak @teju85 for thoughts.

**Comment by wphicks** [comment]
Ah _gen_ eration! Got it, thank you! In that case, I really like the proposed directories. Let me think a bit more about the sparse/graph organization; I'm not sure myself just yet.
