### ISSUE TITLE
[FEA] Move benchmarking infrastructure from cuml

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#495]
Putting the infrastructure in RAFT will allow us to keep benchmarks for the RAFT prims close to the prims and will still allow us to use it in cuml downstream for benchmarking the end-to-end estimators. 

We need to also investigate whether we want to use Nvbench or gbench, so this may not be a straightforward copy from cuml.

cc @tfeher @achirkin @dantegd

**Comment by teju85** [comment]
Just one request here: Can we please switch over to using nvbench, instead of google benchmark?

**Comment by achirkin** [comment]
Current state.
Initial setup is done in https://github.com/rapidsai/raft/pull/549 . Though at this moment, that PR is still using gbench, and only one benchmark is copied from cuml as an example.

**Comment by cjnolet** [comment]
@achirkin now that tthe infrastructure has been moved over, can we close this issue? If we still want to investigate nvbench, I think we should open a separate issue.

**Comment by achirkin** [comment]
There are also a few files in cuml's bench/prims, which benchmark raft functions and can be moved as well (e.g. distance, matrix_vector_op). Shall we then (a) move them while tracking the progress in this issue, (b) create a separate issue for moving them, or (c) just leave them in cuml?

**Comment by cjnolet** [comment]
@achirkin i think tracking progress in this issue is fine. I think we should get these moved over soon though because they are also causing some build timeout issues in cuML’s CI when trying to remove the metrics and stats files (which have already been moved to raft).
