### ISSUE TITLE
[FEA] Optimize span class with static extent

### ISSUE THREAD

**Issue by trivialfis** [rapidsai/raft#511]
As suggested by @jrhemstad in https://github.com/rapidsai/raft/pull/399#discussion_r808190024 we can make sure the compiler knows when to remove the size variable by specializing over static/dynamic extent for the span class.

**Comment by jakirkham** [comment]
Maybe meant @jrhemstad ?

**Comment by trivialfis** [comment]
Oops, sorry! Thank you for pointing that out.

**Comment by jakirkham** [comment]
No worries 🙂
