### ISSUE TITLE
[BUG] Fused L2 kNN is broken for larger inputs

### ISSUE THREAD

**Issue by zbjornson** [rapidsai/raft#568]
**Describe the bug**
The new fused L2 kNN implementation (ccd5d755719cd6be570405d618de485b62202ca2) doesn't work properly for certain sizes(?) of input data and causes at least t-SNE and UMAP in cuML to fail. I don't know the exact criteria to trigger this, but there's a repro below.

**Steps/Code to reproduce bug**
```cpp
#include <cstdint>
#include <cstddef>
#include <iostream>
#include <vector>
#include <random>
#include <cuml/manifold/tsne.h>
#include <raft/handle.hpp>
#include <rmm/device_uvector.hpp>

void make_blobs(float* data, std::size_t nRows, std::size_t nCols, std::size_t nClust) {
	std::random_device rd{};
	uint64_t randomSeed = rd();

	std::mt19937 gen(randomSeed);
	std::uniform_real_distribution<float> urd{};

	std::vector<std::normal_distribution<float>> generators;
	for (size_t i = 0; i < nClust * nCols; i++) {
		float mean = 100 * urd(gen);
		float stdDev = 10 * urd(gen);
		generators.push_back(std::normal_distribution<float>{mean, stdDev});
	}

	for (size_t j = 0; j < nCols; j++)
		for (size_t i = 0; i < nRows; i++)
			data[j * nRows + i] = generators[(i % nClust) * nCols + j](gen);
}

int main() {
	raft::handle_t handle;
	auto stream = handle.get_stream();

	std::size_t nRows = 131'072; // 🥴 100'000 won't trigger it, not sure what exact criteria is
	std::size_t nCols = 8;

	ML::TSNEParams params{
		.dim=2,
		.n_neighbors=60,
		.perplexity=20,
		.max_iter=1500,
		.min_grad_norm=0.f,
		.algorithm=ML::TSNE_ALGORITHM::FFT
	};

	float* hdata = new float[nRows * nCols];
	make_blobs(hdata, nRows, nCols, 8);
	rmm::device_uvector<float> in(nRows * nCols, stream);
	raft::update_device(in.data(), hdata, nRows * nCols, stream);
	delete[] hdata;

	rmm::device_uvector<float> out(nRows * params.dim, stream);

	float klDiv;

	ML::TSNE_fit(
		handle,
		in.data(),
		out.data(),
		nRows,
		nCols,
		nullptr,
		nullptr,
		params,
		&klDiv
	);

	std::cout << "KL-div: " << klDiv << std::endl;
}
```

Compile with `g++ -o test test.cpp -m64 --std=c++17 -I/usr/local/cuda/include -I/usr/local/include/raft -L/usr/local/cuda/lib64 -lcuda -lcuml++ -lcufft -lcusolver -lcublas -lcusparse -lcudart`.

With the fused kernel enabled, this takes ~30 seconds to run and prints `KL-div: nan` (and the embeddings are nonsense). With it disabled, it takes ~4 seconds and has a KL-div of about 0.6.

**Environment details (please complete the following information):**
 - Environment location: Google Cloud Platform
 - Method of RAFT install: from source
 - cuML based on 22.02 branch
 - Hardware: V100

**Comment by cjnolet** [comment]
cc @mdoijade for awareness

**Comment by mdoijade** [comment]
@cjnolet Thanks for informing, I will repro and debug.

**Comment by mdoijade** [comment]
update: I've a repro with the given code, investigating fix. Thanks

**Comment by cjnolet** [comment]
@zbjornson a fix for this was merged today. Can you test with the latest raft version (22.06 branch) and let us know if the problem has been solved?

**Comment by zbjornson** [comment]
> happens when rows are multiple of 256

Heh, go figure that my benchmarking loop runs in powers of 2.

Confirmed fix, thanks @mdoijade.
