### ISSUE TITLE
[DOC] mdspan/mdarray quick-start tutorial

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#654]
As both RAFT and downstream projects begin to increase their use of the mdspan/mdarray APIs, we need a good comprehensive tutorial or `quick-start` in the RAFT docs that can help users quickly start using these APIs. 

Some general use-cases so far:

1. Basic mdarray/mdspan usage and creation on host
2. Invoking functions that accept mdarray/mdspan
3. Building functions that accept mdarray/mdspan
4. Using mdspan/mdarray in device functions
5. Using mdspan/mdarray around shared memory. 
6. Creating custom container and accessor policies
7. Creating custom layout policies 

cc @trivialfis, @divyegala, @akifcorduk, @rg20, @mfoerste4, @wphicks, @teju85 what other things should be added to this list?

**Comment by rg20** [comment]
I guess a note on similarities and differences with std::mdarray would be helpful. For mdspan, we should be good since raft already uses std::mdsapn if I am not wrong.

**Comment by trivialfis** [comment]
> I guess a note on similarities and differences with std::mdarray would be helpful.

It's still an early proposal, we might not want to reference it too much as both designs are evolving.

**Comment by mhoemmen** [comment]
Hi all!  mdspan does have existing tutorial material to which the RAFT docs could link.  It also has examples and tests that could be used to build tutorials.

> 1. Basic mdarray/mdspan usage and creation on host

["A gentle introduction to mdspan"](https://github.com/kokkos/mdspan/wiki/A-Gentle-Introduction-to-mdspan) could address this.

> 6. Creating custom container and accessor policies
> 7. Creating custom layout policies

Some examples in the reference mdspan implementation, either in the main branch or in PRs, show how to do this.  Examples include

* [`restrict_accessor`](https://github.com/kokkos/mdspan/tree/stable/examples/restrict_accessor),
* [`aligned_accessor`](https://github.com/kokkos/mdspan/pull/176), and
* [tiled layout](https://github.com/kokkos/mdspan/tree/stable/examples/tiled_layout) (which could use a small update).

The examples aren't really a tutorial, but a tutorial could annotate and explain them.

Some mdarray tests show useful techniques.  For example, [the mdarray constructor tests](https://github.com/kokkos/mdspan/blob/stable/tests/test_mdarray_ctors.cpp) illustrate use of mdarray with a `std::vector` using a custom `std::pmr::memory_resource`.  Again, that's a test, not even an example, but it could form the beginning of an example.

Note that [the reference implementation of mdarray](https://github.com/kokkos/mdspan) implements the latest version (R3 as of 2022/08/23) of [the mdarray proposal P1684](https://wg21.link/p1684).  The version of mdarray currently being used in RAFT is an older version that has a "container policy" template parameter.  The latest version takes the "container" type directly as a template parameter.

**Comment by mhoemmen** [comment]
@trivialfis wrote:
> Aside from these, I enjoy the submdspan so much, we might want to briefly mention it somewhere.

Awww, thanks! : - D  Our `submdspan` paper just came out this month: https://wg21.link/p2630 .  Please note two new features.

1. New slice specifier: `strided_index_range`
2. Support for slice specifiers that store integer values as `std::integral_constant`, so that the return type can encode this information at compile time
