### ISSUE TITLE
[FEA] support for "condensed distance matrix" as in scipy.spatial.distance.pdist

### ISSUE THREAD

**Issue by teju85** [rapidsai/raft#661]
**Is your feature request related to a problem? Please describe.**
[scipy.spatial.distance.pdist](https://docs.scipy.org/doc//scipy-1.2.3/reference/generated/scipy.spatial.distance.pdist.html) computes the pairwise distance but returns a compacted/condensed matrix in the upper triangular (minus diagonal) form. This makes sense since distance of a point with itself is zero and the distance metrics supported are all symmetric.

**Describe the solution you'd like**
We should have our pairwise distances API to also provide this output format when requested. This topic came up when @cjnolet and I were on a call today.

**Describe alternatives you've considered**
Alternative is to compute the pairwise distances in the dense matrix format and then condense afterwards. But it requires extra memory that could be prohibitive at times.

JFYI @tfeher and @mdoijade

**Comment by cjnolet** [comment]
Also linking https://github.com/rapidsai/raft/issues/650 (cc @teju85)

**Comment by teju85** [comment]
ah... you beat me to it @cjnolet ! I should have checked first. Thanks. Closing this issue.
