### ISSUE TITLE
[BUG] Intermittent failures for the KL Divergence GTests

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#716]
This has popped up several times now in CI and I've yet to see these locally. The first couple times I saw it, I thought maybe it was just a fluke but now it's happened enough times that it's worth investigating the cause.

**Comment by cjnolet** [comment]
Here's an example of the failure in CI. 

https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/raft/job/prb/job/raft-gpu-test/CUDA=11.0,GPU_LABEL=driver-450,LINUX_VER=centos7,PYTHON=3.8/1556/console

cc @mdoijade

**Comment by mdoijade** [comment]
Thanks for informing, I'm work towards fixing this, from log file seems like naive test kernel has a bug whereas main kernel is generating correct output.

**Comment by mdoijade** [comment]
this issue is fixed, should be good to close this.
