### ISSUE TITLE
[BUG] Memory leak when mdarray is used in a file that is used by cython/python interface

### ISSUE THREAD

**Issue by rg20** [rapidsai/raft#740]
**Describe the bug**
When using mdarray in C++ code alone, it works as expected. However, when using the python interface, we get memory issues such as: 

- Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
- munmap_chunk(): invalid pointer, Aborted (core dumped)
- corrupted double-linked list. Aborted (core dumped)

**Steps/Code to reproduce bug**
A PR in cuOpt that reproduces the bug is here: https://github.com/rapidsai/cuopt/pull/605. In this PR, mdarray is declared as a member variable in a class and not at all used (null op) 

**Expected behavior**
The C++ version is working just fine.  The `mdarray` (in this case) is not part of the cython or python class, so it should work fine. 

**Environment details (please complete the following information):**
 cuOpt needs to be installed to reproduce the bug. There may be other projects (like cuGraph) that can be used to reproduce the bug. 
 
**Additional context**

**Comment by afender** [comment]
We are getting close to release and impacted authors will go on PTO soon. Unless this is a quick fix that can happen this week, cuOpt should fall back on rmm for 22.08.

**Comment by tfeher** [comment]
Note that cuML had the same issue: segfault during the destruction of objects, if we were wrapping a class with an mdarray class member (https://github.com/rapidsai/cuml/pull/4823).

The current workround is to replace the `device_mdarray`s with `device_uvector`s https://github.com/achirkin/raft/commit/8b267506f4f48936a6609d8d7d1866eca754bd56

**Comment by tfeher** [comment]
This looks like a similar issue: https://github.com/rapidsai/rmm/pull/931
