### ISSUE TITLE
[FEA] IVF-flat serialization

### ISSUE THREAD

**Issue by tfeher** [rapidsai/raft#752]
**Is your feature request related to a problem? Please describe.**
cuML will need to serialize/deserialize the `ivf_flat::index` (see https://github.com/rapidsai/cuml/issues/4743).  Some other downstream libraries might want to do the same thing. 

It would be easier if RAFT provides methods to save / restore the state from simple byte strings.

**Describe the solution you'd like**

- Provide serialize  method that return host byte string with the index state.
- Provide a deserialize method that creates an index from a byte string.

**Describe alternatives you've considered**
The new IVF flat code #747 provides accessors for the index state, so it is possible for each library to roll out their preferred serialization method. This requires downstream library developers to understand (part of the) implementation details of the index. It would be easier if RAFT provides the serialization method.

**Comment by teju85** [comment]
@cjnolet and I had a long discussion around this topic. Thought it would if a short summary of this discussion was provided here:

Pros of RAFT providing serialization APIs:
1. Code reusability.
2. Users don't have to worry about serialization

Cons:
1. Users are restricted to the way we serialize (although they could technically use the index structures we expose and write their own serialization methods)

**Comment by cjnolet** [comment]
@tfeher I think this issue has been addressed. Can it be closed?
