### ISSUE TITLE
API Proposal w/ `std::experimental::mdspan` and "execution environments"

### ISSUE THREAD

**Issue by divyegala** [rapidsai/raft#769]
This issue is to discuss the possible directions RAFT's API can take with the usage of `std::experimental::mdspan` (targetted C++23) and what we refer to as "execution environments".

_**Execution Environments**_
The idea is similar to how `thrust` facilitates execution on host or device using `thrust::host/device`. The context denotes compile-time or run-time dispatch as desired, unaware of whether the underlying memory is on host or device (or managed). The environment will then hold resources common and unique to e

The above design is then further facilitated by the usage of `mdspan`, yet we must answer an important question:
**Memory (Un)aware buffers**

**_- Vanilla `std::experimental::mdspan`_**
_Pros_

1. Soon-to-be part of the standard
2. Users can extend to create their own wrappers for extra features and the API will directly support these sub-classes
3. The execution environment will denote whether to run the operation on host or device
4. Can support run-time and compile-time dispatch to host/device

_Cons_

1. No compile-time indication of whether the chosen host/device path will work. For eg. user will find errors at run-time if they use device execution environment with `mdspan` buffers that point to host memory
2. User has to keep track of where the memory lies in some other fashion since the type has no information about that
3. Harder to interact with `mdarray` as the returned view type will again lose information of host/device memory

_Potential look of API_
```
void foo(execution_environment, mdspan<...> buffer, ...);
```

**_- Wrappers around `std::experimental::mdspan` of the form `raft::device/host_mdspan'_**
_Pros_

1. Compile-time knowledge of types, thus knowing beforehand where the memory lies
4. Easy-to-use factories for users to keep track of where the memory is based on the type
5. Easier interaction with `mdarray` and its container type. A device container should return a `device_mdspan` view

_Cons_

1. Users will need to extend RAFT's wrappers to create their own wrappers
2. There's slight brittleness because one could create a `device_mdspan` with a host pointer
6. Redundancy of execution environment, which will still need to be device/host specific 
7. No run-time dispatch

_Potential look of API_
```
void foo(execution_environment, device_mdspan<...> buffer, ...);
```

**_Possible Alternatives:_**
A combination of both the above APIs in terms of overloads. Vanilla `mdspan` API run-time dispatches to wrapper-based `mdspan` API with the help of either the execution environment or by querying the underlying memory for its location using CUDA Driver APIs

**Comment by mhoemmen** [comment]
The idiomatic way to ensure device accessibility at compile time would be to use (stock) `mdspan` with a custom accessor type whose `access` function only compiles when inside device code.  Is that what "wrapped" mdspan means, or are you actually subclassing mdspan?  Subclassing mdspan would be unnecessary in this case, because the accessor type alone suffices to express the idea, and because subclassing mdspan would make specialization harder.

**Comment by viclafargue** [comment]
I would say that the location of the input data should not decide the function that will be called. Instead the execution environment should prevail and automatically trigger transfers when necessary. Let's say that we train a model on the device and then want to make inferences on the host. The intermediate data (or model's attributes in Python) would be located on the GPU. We would like that data to be transferred to the host during its access inside the host API calls. This could alternatively be taken care of elsewhere before the call, but it looks like a good idea to by using this process ensure that all the required data and only it gets transferred just before its use.

To that end, we could have an attribute in the mdspan class that would specify the location of the data (might possibly include managed memory). We could then make use of a templated accessor that would check the execution environment at runtime and if necessary trigger a transfer, release old data and update and provide the new pointer. As previously said, avoiding subclasses would allow further external work/extension on mdspan. The attribute would avoid (potentially costly?) calls to the CUDA API.
 
Then to write the API calls functions themselves, we could have the execution environment as a non-type template parameter. That way we could write separate host/device functions and when similar enough group them and make use of compile-time conditions.

**Comment by trivialfis** [comment]
> The idiomatic way to ensure device accessibility at compile time would be to use (stock) mdspan with a custom accessor type

We have been doing that to some extend, take a look at the `host_mdarray` and `device_mdarray` defined in raft. But making the access function device only is a great suggestion!

> I would say that the location of the input data should not decide the function that will be called. 

Totally agree!  There should be a single source of information on where to run the function, ideally that would be the handle/context object. Otherwise, we will end up with lots of conflicts like whether should we run prediction if the model is trained on GPU but test data is on CPU however the sample weight is also on GPU, etc. (number one headache in XGBoost)

Have you taken a look at other libraries like tensorflow or pytorch? They have been dealing with this since day 1.

**Comment by divyegala** [comment]
@trivialfis @viclafargue I completely agree with both of your assessments of the situation. The location of the data will not determine where the function will be run, but will rather help us throw compile-time/run-time errors that an invalid configuration has been called. Whether we go the direction of copying the data for the user is another matter, but combined with the execution environment and knowing the location of the data (device, host, managed) I believe we should be able to implement the design patterns both of you mentioned.

**Comment by mhoemmen** [comment]
[viclafargue](https://github.com/viclafargue) wrote:
> We could then make use of a templated accessor that would check the execution environment at runtime and if necessary trigger a transfer, release old data and update and provide the new pointer. 

`mdspan` is nonowning.  Thus, I would strongly discourage giving mdspan or its accessor any control over memory transfers or allocation.  It would be better to have some other type (possibly mdarray, but see below) govern these automatic transfers.

Other programming environments have a separate type for "an owning handle to data that might live on host or device."  Kokkos calls this `DualView`; SYCL calls this a buffer (vs. an accessor, which is more mdspan-like).  I personally prefer a declarative callback interface.

```c++
template< /* ... same as mdarray, possibly */ >
class opaque_buffer;

// Even though we know we have a 3-D mdspan of double,
// being generic on the Layout gives memory transfers the freedom
// to use the optimal memory layout.
//
// device_accessor says that the elements of x
// can only be accessed in a device kernel.
template<class Layout, class IndexType, size_t ... Extents>
requires(is_integral_v<IndexType> && sizeof...(Extents) == 3)
void fill_on_device_with_magic_numbers(
  mdspan<double, extents<IndexType, Extents...>, Layout, device_accessor<ElementType>> x)
{
  some_device_kernel<<<...>>>(x);
}

// Not even necessarily allocated yet.
// No interface to access the elements directly.
// All access happens by getting an mdspan via with_local_access.
opaque_buffer<double> x_buf{3, 4, 5};

// .on(gpu(stream)) means "access on the GPU, using the given stream."
// Write-only access means we don't have to copy from host to device.
// It also means that we can allocate the buffer, if it's not yet allocated.
// That, plus .on(gpu(stream)), means we can use cudaMallocAsync.
with_local_access(write_only(x_buf).on(gpu(stream)), fill_on_device_with_magic_numbers);
```
