### ISSUE TITLE
[FEA] also reconcile error_utils from cugraph

### ISSUE THREAD

**Issue by teju85** [rapidsai/raft#8]
**Is your feature request related to a problem? Please describe.**
As mentioned by @afender [here](https://github.com/rapidsai/raft/pull/3#discussion_r416683440), it would be nice to also merge common parts of cugraph into RAFT, especially the error_utils component.

**Describe the solution you'd like**
RAFT error_utils must be an intersection of commonalities between cuml and cugraph.

**Describe alternatives you've considered**
For the initial version, it consists of stuff from cuml only!

**Comment by seunghwak** [comment]
I think https://github.com/rapidsai/raft/pull/15 addressed this, so we can close this issue.
