### ISSUE TITLE
[FEA] Should a `device_span` and `host_span` just be an mdspan w/ 1-d extents?

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#817]
This discussion has come up a few times and I think it's a good idea that we come to a conclusion. A span is a very lightweight abstraction over a pointer and number of elements, which the mdspan also provides. Thus, a span can be viewed as a 1-dimensional mdspan with the default accessor and assumed contiguous layout. What else does the span provide? Should we just alias `host_span` -> `host_mdspan<1-d extents>` and `device_span` -> `device_mdspan<1-d extents>`? 

Tagging the usual folks: @mhoemmen @trivialfis @divyegala @seunghwak @akifcorduk @rg20 @achirkin @wphicks

**Comment by mhoemmen** [comment]
@cjnolet The only argument against this is that `span` has a different interface than `mdspan`.

1. `span` has iterators; `mdspan` does not.
2. `span` has `.data()`; `mdspan` has `.data_handle()`.

If users see `something_span`, then they might imagine that it has the same interface as `span`.  On the other hand, I think that's not a big deal.  Users might try `s.begin(), s.end()`, find out it doesn't compile, then do `s.data_handle(), s.data_handle() + s.size()` and continue on with their lives.  The latter only becomes a big deal if we want to change `data_handle_type` to do (say) bounds checking, but even that shouldn't matter as long as it's a contiguous iterator.

**Comment by wphicks** [comment]
I'd +1 everything @mhoemmen has to say here but also add that `span` is enough simpler of an object that I think there is benefit in maintaining it separately merely for the sake of allowing developers to more quickly iterate on `span` independent of the more complex considerations of `mdspan`.

**Comment by trivialfis** [comment]
Late to the discussion here, apologies. To me span is still a convenient class to have. We have a host_vector class in mdarray but we might still want to use std::vector to store sequence of variables.

**Comment by mhoemmen** [comment]
@trivialfis wrote:
> In a similar way, span is a view to general storage like std vector or rmm vector, while mdspan is more specific to linear algebra.

To me, the difference is about storage and access.  A span `s` always represents a sequence of elements

1. stored in memory
2. for which `(s.data())[k]` gives you a reference (`ElementType&`)
3. to the k-th element.

None of these need to be true for mdspan.  The elements don't have to be in memory.  (They could live on disk, across the network, or be computed on the fly.)  If they are stored in memory, they don't have to be stored contiguously; the order could be arbitrary, and there's no promise that the entire [0, `required_span_size()`) range be valid to access through pointer dereference.  (The accessor could do indirect access via an index array, for example.)  Furthermore, the elements aren't necessarily accessed through `ElementType` pointer dereference.  (Compare to `std::vector<bool>`, which does not store an array of `bool`.)
