### ISSUE TITLE
[FEA] Deploy raft globally

### ISSUE THREAD

**Issue by afender** [rapidsai/raft#83]
Currently, each repo carries its own RAFT under its own include directory. The versions of the different copies are not necessarily the same. 

Ideally, we would adopt RMM style for global deployment of RAFT.

That mostly requires

- always supporting the latest raft version
- shipping a new conda package

**Comment by divyegala** [comment]
Now that cuML and cuGraph both point to HEAD in RAFT, is this still a valid issue? cc @dantegd
