### ISSUE TITLE
[BUG] Build failures in ivf_pq_search.cuh

### ISSUE THREAD

**Issue by benfred** [rapidsai/raft#940]
**Describe the bug**

Building on my development box fails in `cpp/include/raft/spatial/knn/detail/ivf_pq_search.cuh` ..

The build failures seem to be related to C++17 `if constexpr` code. This causes some false positive  warnings about declared variables not being referenced, which cause build failures because of the `-Werror` flag.

I suspect this is because I'm using an older version of NVCC/ G++ than whats expected.

The specific errors are:
```
/home/ben/code/raft/cpp/include/raft/spatial/knn/detail/ivf_pq_search.cuh(659): error: variable "out_indices" was declared but never referenced
          detected during:
            instantiation of "void raft::spatial::knn::ivf_pq::detail::ivfpq_compute_similarity_kernel<OpT,IdxT,OutT,LutT,Capacity,PrecompBaseDiff,EnableSMemLut>(uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, raft::distance::DistanceType, raft::neighbors::ivf_pq::codebook_gen, uint32_t, const float *, const float *, const uint8_t *, const IdxT *, const uint32_t *, const uint32_t *, const float *, const uint32_t *, LutT *, OutT *, IdxT *) [with OpT=uint8_t, IdxT=uint32_t, OutT=half, LutT=float, Capacity=0, PrecompBaseDiff=true, EnableSMemLut=false]" 
```

```
/home/ben/code/raft/cpp/include/raft/spatial/knn/detail/ivf_pq_search.cuh(635): error: variable "base_diff" was declared but never referenced
          detected during:
            instantiation of "void raft::spatial::knn::ivf_pq::detail::ivfpq_compute_similarity_kernel<OpT,IdxT,OutT,LutT,Capacity,PrecompBaseDiff,EnableSMemLut>(uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, raft::distance::DistanceType, raft::neighbors::ivf_pq::codebook_gen, uint32_t, const float *, const float *, const uint8_t *, const IdxT *, const uint32_t *, const uint32_t *, const float *, const uint32_t *, LutT *, OutT *, IdxT *) [with OpT=uint64_t, IdxT=uint64_t, OutT=half, LutT=raft::spatial::knn::ivf_pq::detail::<unnamed>::fp8u_t, Capacity=0, PrecompBaseDiff=false, EnableSMemLut=true]" 
```

```
/home/ben/code/raft/cpp/include/raft/spatial/knn/detail/ivf_pq_search.cuh(101): error: missing return statement at end of non-void function "raft::spatial::knn::ivf_pq::detail::fp_8bit<ExpBits, Signed>::float2fp_8bit [with ExpBits=5U, Signed=false]"
```

**Steps/Code to reproduce bug**

Run `./build.sh libraft tests --compile-libs  --cache-tool=ccache`. 

**Environment details (please complete the following information):**
 - Environment location: Bare-metal
 - Method of RAFT install:  source

I'm using Cuda 11.4 and GCC 9.4 on  Ubuntu 20.04
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Aug_15_21:14:11_PDT_2021
Cuda compilation tools, release 11.4, V11.4.120
Build cuda_11.4.r11.4/compiler.30300941_0

$ g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by benfred** [comment]
Fwiw, I can make the build to work by disabling the specific warnings in ivf_pq_search.cuh with code like:

```c++
#pragma diag_suppress 177
#pragma diag_suppress 940
```

**Comment by tfeher** [comment]
When using an older gcc version (7.5) I run into a similar problem in pow2 utils. This also relates to `if constexpr` code that is not discarded, and therefore it triggered an error. This particular problem goes away with gcc 8.2 or above, IIUC doe to improved handling of constexpr conditions.

```
raft/cpp/include/raft/util/pow2_utils.cuh:140:52: error: cast from ‘const float*’ to ‘raft::Pow2<8>::Type {aka int}’ loses precision [-fpermissive]

 if constexpr (Pow2_IS_REPRESENTABLE_AS(PtrT)) return (p + PtrT(Mask)) & PtrT(~Mask);

                                               ~^~~~~~~~~~~~~~~~~~~~
```

@cjnolet I suggest that we document somewhere what is the minimum GCC version needed to compile raft.

**Comment by benfred** [comment]
I think this might be the NVCC version that is causing the build failures, rather than the g++ version - for a couple of reasons:
* Building on a docker container with cuda 11.7 and g++ 9.4 works for me, but building on my host machine with cuda 11.4 and g++ 9.4 fails as described above
* The warnings causing the build failure occur in a cuda kernel, and can be suppressed by adding nvcc pragma’s rather than the equivalent g++ pragma

The weird thing is that I see CI building with cuda 11.2 and 11.5 - so its a little odd that I’m getting failures with cuda 11.4

**Comment by cjnolet** [comment]
@tfeher @benfred minimim gcc version has been added to the build docs (docs/source/build.md)

**Comment by benfred** [comment]
The build failures seem to be related to my conda environment - which had a 11.6 CTK, even though I am using cuda 11.4. Upgrading to a clean conda environment fixed for me.
