### ISSUE TITLE
[FEA] Use RMM directly instead of adapters

### ISSUE THREAD

**Issue by divyegala** [rapidsai/raft#97]
We should use RMM’s device buffers/device uvectors directly and it has a ton of advantages over raft/cuml device buffers such as:
1. C++11/14 features of using copy/move constructors and assign operators. This will be a blessing to work with and allow us to take ownership of data across APIs without the need to copy
2. Allowing us to take ownership of raw pointers and storing it in buffers. This is especially beneficial as the size is stored in the buffer object and will help us minimize the confusion at least at a developer level by having to pass explicit multiple size arguments between functions and create a barrier from out of bounds accesses
3. Using vanilla RMM shifts the dependency from us having to maintain our own buffers (with RMM under the hood) to instead allowing for RMM to maintain the API

**Comment by teju85** [comment]
#### Why we ended up designing our own interfaces for allocators and buffers in cuML?

During the initial days, there were a couple of customers interested in directly using libcuml++. But they wanted tighter control over allocators, buffers, threaded-ness, etc. Sadly, we never heard back from them afterwards! Let me check internally and get back here about its status.

#### My opinion
Agree with Divye. We should just go ahead with as much reuse as possible from RMM. It also makes our code more uniform and in-line with the design of other RAPIDS components too.

**Comment by seunghwak** [comment]
Cannot agree more with this :-)

**Comment by dantegd** [comment]
I don't think we have heard a single dev/stake holder that has not been in agreement with the proposal.

**Comment by teju85** [comment]
@divyegala and/or @dantegd any plans on getting this implemented in raft soon? Because of this, we cannot enable RMM at cuML side (as described in #228), which is needed to reduce malloc/free overheads on one of the customer workloads.

**Comment by viclafargue** [comment]
Closed by #286
