### ISSUE TITLE
[FEA] Port CAGRA to RAFT

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#997]
Cagra is a new state of the art graph-based nearest neighbors method which is currently showing great query performance for both large and small batch sizes. Adding a placeholder here to track it's port onto raft primitives.

**Comment by S-o-T** [comment]
Can you please share a link to the paper?

**Comment by cjnolet** [comment]
Hi @S-o-T, not paper yet but I can share a few initial benchmark results with you.

![Screenshot from 2023-02-13 11-52-10](https://user-images.githubusercontent.com/1242464/218521036-b7c42012-9507-4b36-b4ab-710fc178a61a.png)
![Screenshot from 2023-02-13 11-52-20](https://user-images.githubusercontent.com/1242464/218521037-a6f3e4f4-fa25-4825-8dbe-c4d9d4bcb8f2.png)
![Screenshot from 2023-02-13 11-52-33](https://user-images.githubusercontent.com/1242464/218521040-6b7e0f29-a110-4f9e-8885-de581515bc71.png)
![Screenshot from 2023-02-13 11-52-36](https://user-images.githubusercontent.com/1242464/218521041-ad64da7a-4fd6-4805-9130-70459cf6953d.png)
![Screenshot from 2023-02-13 11-52-49](https://user-images.githubusercontent.com/1242464/218521042-dd2c8ef7-83ae-4470-9bda-925d08db70a8.png)

Is this helpful?

**Comment by S-o-T** [comment]
Thanks a lot! Looks promising indeed.

Also, would be nice to understand costs for index building. I am wondering, if this approach can outperform brute-force matching of sift features, so the cost of building an index might be a problem.

What is current ETA?

**Comment by cjnolet** [comment]
@S-o-T, currently implementation uses nn-descent in the index building process so it should be very fast and competitive. I can see about getting benchmarks for index construction as well. 

Current ETA is going to be around 23.06 release at the earliest (June release) but more realistically it might be later before it's fully integrated.

**Comment by S-o-T** [comment]
@cjnolet And by that time, the integration to faiss planned to be finished and this approach would be accessible via faiss api?

**Comment by cjnolet** [comment]
@S-o-T, the timeframe for Cagra integration into FAISS is tentative at the moment, but yes it will be accessible eventually. We are more likely to see RAFT's IVF-FLAT/IVF-PQ fully integrated by 23.06/23.08 timeframe.

**Comment by xiaofan-luan** [comment]
Hi @cjnolet，impressive work! do we have performance number compared to cpu graph index in the similar dataset?

**Comment by cjnolet** [comment]
@xiaofan-luan unfortunately none that I'm able to share quite yet. I can say we are finding speedup over HNSW for small batch performance. There will be more details [this GTC session](https://www.nvidia.com/gtc/session-catalog/?ncid=pa-srch-goog-148470-prsp-sl1&tab.catalogallsessionstab=16566177511100015Kus&search=Akira#/session/1666620202078001m87I) will provide more details and benchmarks against HNSW and GGNN.

**Comment by cjnolet** [comment]
@S-o-T @xiaofan-luan I have been given the okay to share some benchmarks that compare CAGRA with HNSW and GGNN: 
[Perf-comparision.20230220 (2).pdf](https://github.com/rapidsai/raft/files/10794201/Perf-comparision.20230220.2.pdf)

@S-o-T as requested, here are some initial benchmarks of CAGRA index building times against HNSW and GGNN. Are there any specific data sets/sizes/scales that you are interested in comparing CAGRA index building against? 

[ANNS-indexing-time.20230221.xlsx](https://github.com/rapidsai/raft/files/10794225/ANNS-indexing-time.20230221.xlsx)

**Comment by xiaofan-luan** [comment]
> @S-o-T @xiaofan-luan I have been given the okay to share some benchmarks that compare CAGRA with HNSW and GGNN: [Perf-comparision.20230220 (2).pdf](https://github.com/rapidsai/raft/files/10794201/Perf-comparision.20230220.2.pdf)
> 
> @S-o-T as requested, here are some initial benchmarks of CAGRA index building times against HNSW and GGNN. It builds the indexes using `nn-descent`, though first version of CAGRA may use the ivf-pq which is already in RAFT. Are there any specific data sets/sizes/scales that you are interested in comparing CAGRA index building against?
> 
> [ANNS-indexing-time.20230221.xlsx](https://github.com/rapidsai/raft/files/10794225/ANNS-indexing-time.20230221.xlsx)

The index building time of HNSW seems to be incredibly long compare to CPU version. But the search performance under larger batch is very impressive.
Looking forward to integrate RAFT with Knowhere && Milvus !

**Comment by S-o-T** [comment]
@cjnolet Thanks for the slides, looks interesting!

Currently, i am most interested in following scenario: metric = inner product, dim = 128, |database| = 10^3 (also, 2^16), |query| = 10^3, k = 2 (also, k = 1). Both indexing and query processing performance are important, but indexing might by amortized if query processing is fast. It would be interesting to compare with current implementation of faiss GpuFlat and raft's flat alternative (still not found a time to play with raft's nn primitives).

**Comment by cjnolet** [comment]
@S-o-T so it sounds like you are interested in fast ANN at the scale of 10's of thousands? Is this  computation needed to be performed repeatedly or at somewhat interacitve/real-time speeds?

**Comment by S-o-T** [comment]
@cjnolet 
> fast ANN at the scale of 10's of thousands?
Yes, that's my main interest currently.

> Is this computation needed to be performed repeatedly or at somewhat interacitve/real-time speeds?
Not quite, so giving up a lot of quality to get some "real-time" guarantee is not an option, but trading "some" quality to get substantial gains on latency/throughput might be interesting.

**Comment by cjnolet** [comment]
Related PR: https://github.com/rapidsai/raft/pull/1666
